sudo: required
services:
  - docker

branches:
  only:
  - develop
  - /\d+\.\d+(\.\d+)?(-\S*)?/

before_install:
  - docker build -t froger/dmfsu .

script:
  - docker run froger/dmfsu /bin/sh -c "cd /usr/src/app; rails spec;"

after_success:
  - if [[ -n "${TRAVIS_TAG}" ]]; then
    docker tag froger/dmfsu froger/dmfsu:$TRAVIS_TAG;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push froger/dmfsu:$TRAVIS_TAG;
    fi
